#!/usr/bin/env fish

set --erase VG_APP_DIR

set d "/other/directory"

set o (vantage --app "$d" config VG_APP_DIR)

test "$o" = "$d"

set s $status

if test $s -ne 0
    echo "    Thought VG_APP_DIR should be $d, it was $o"
    exit $s
end

set o (vantage -a "$d" config VG_APP_DIR)

test "$o" = "$d"

set s $status

if test $s -ne 0
    echo "    Thought VG_APP_DIR should be $d, it was $o"
end

exit $s
