#!/bin/sh
set -e

echo "Removing any existing vantage installations..."
rm -rf /usr/local/vantage /usr/local/bin/vantage /usr/local/bin/vg

echo "Cloning vantage into /usr/local/vantage..."
git clone https://github.com/vantage-org/vantage.git /usr/local/vantage

echo "Linking script to /usr/local/bin/..."
ln -s /usr/local/vantage/vantage /usr/local/bin/vantage
ln -s /usr/local/vantage/vantage /usr/local/bin/vg

if [ -d /etc/bash_completion.d ]; then
    echo "Linking bash completion script to /etc/bash_completion.d"
    ln -s /usr/local/vantage/complete /etc/bash_completion.d/vantage
    ln -s /usr/local/vantage/complete /etc/bash_completion.d/vg
fi

echo "Done!"
echo "Run 'vantage -h' to see what to do now :)"
