#!/bin/sh
# ---
# help-text: Install this dev version to /usr/local/bin/v3
# requires:
#   - build
# ---
sudo rm -rf /usr/local/bin/v3 /usr/local/v3
sudo cp -r dist/vantage /usr/local/v3
sudo ln -s /usr/local/v3/vantage /usr/local/bin/v3
