#!/usr/bin/env fish
switch "$argv"
    case 'summary'
        echo "  update - Update vantage and plugins"
    case '*'
        echo "\
vantage update
  Update vantage itself
vantage update PLUGIN
  Update specific plugin
  e.g. vantage update pg"
end
