#!/usr/bin/env fish

set o (vantage --app "$d" config FOO)

test "$o" = ""

set s $status

if test $s -ne 0
    echo "    Thought config variable FOO shouldn't exist yet, it was $o"
end

set d (mktemp --directory)
echo "FOO=BAR" > "$d/.vantage"

set o (vantage --app "$d" config FOO)

rm -rf "$d"

test "$o" = "BAR"

set s $status

if test $s -ne 0
    echo "    Thought config variable FOO should be BAR, it was $o"
end

exit $s
