#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob

case "$1" in
    run)
        docker run \
            --env-file "$VG_ENV_FILE" \
            --interactive \
            --tty \
            vg_app
        exit $VG_VALID_EXIT
        ;;
    help)
        echo "    app run - 0. Run an interactive shell"
        ;;
    *)
        exit $VG_NOT_IMPLEMENTED_EXIT
        ;;
esac
