#!/usr/bin/env fish

set f (mktemp)
echo "TEST_ENV_ENV_VAR_ONE=ONE" > "$f"

set o (vantage --env "$f" --var TEST_ENV_ENV_VAR_TWO=TWO env TEST_ENV_ENV_VAR_ONE)

test "$o" = "ONE"

set s $status

if test $s -ne 0
    echo "    Thought ENV variable TEST_ENV_ENV_VAR_ONE should be ONE, it was $o"
    exit $s
end

set o (vantage --env "$f" --var TEST_ENV_ENV_VAR_TWO=TWO env TEST_ENV_ENV_VAR_TWO)

test "$o" = "TWO"

set s $status

if test $s -ne 0
    echo "    Thought ENV variable TEST_ENV_ENV_VAR_TWO should be TWO, it was $o"
    exit $s
end

exit $s
