#!/usr/bin/env fish

set pass 0

vantage env FOO BAR
vantage env TWICE ONE
vantage env TWICE TWO

set o (vantage env FOO)

test "$o" = "BAR"

set s $status

if test $s -ne 0
    echo "    Thought the env variable FOO should be BAR, it was $o"
    set pass 1
end

set o (vantage env TWICE)

test "$o" = "TWO"

set s $status

if test $s -ne 0
    echo "    Thought the env variable TWICE should be TWO, it was $o"
    set pass 1
end

exit $pass
