#!/usr/bin/env fish
switch "$argv"
    case 'summary'
        echo "  plugins - Manage vantage plugins"
    case '*'
        echo "\
vantage plugins list
  Show a list of installed plugins
vantage plugins install NAME|URL
  Install a new plugin
  NAME - Install official vantage plugin by name
    e.g. vantage plugins install pg
  URL - Install plugin via git url
    e.g. vantage plugins install https://github.com/vantage-org/pg.git
vantage plugins uninstall NAME
  Remove an installed plugin
    e.g. vantage plugins uninstall pg
vantage plugins update NAME
  Update a plugin to the latest version
vantage plugins which NAME
  Find where a plugin is installed"
end
