#! /usr/bin/env fish

set d_update (dirname (status --current-filename))
set d_core (dirname "$d_update")
set d_plugins (dirname "$d_core")

switch "$argv[1]"
    case 'list' 'ls'
        ls -1 "$d_plugins/installed"
    case 'install' 'add'
        set name "$argv[2]"
        if test "$name" != "http?://*"
            set name "https://github.com/vantage-org/$name.git"
        end
        mkdir -p "$d_plugins/installed"
        cd "$d_plugins/installed"
        git clone "$name" --recursive
    case 'uninstall' 'remove'
        rm -rf "$d_plugins/installed/$argv[2]"
    case 'update'
        vantage update "$argv[2]"
    case 'which' 'where' 'find'
        if test (count $argv) -lt 2; vantage help plugins; exit 1; end
        for path in $VG_PLUGIN_PATH
            for plugin in (ls "$path")
                if test -f "$path/$plugin/aliases"
                    set aliases (cat "$path/$plugin/aliases")
                end
                contains "$argv[2]" "$aliases"
                if test $status -eq 0 -o "$plugin" = "$argv[2]"
                    echo "$path/$plugin"
                    exit 0
                end
            end
        end
    case '*'
        vantage help plugins
end
