#!/usr/bin/env fish

set pass 0

source "$VG_INSTALL_DIR/functions"

if not get_arg_flag "command --flag" "--flag"
    echo "Expecting --flag to be flagged"
    set pass 1
end

if get_arg_flag "command --flag" "-f"
    echo "Not expecting -f to be flagged"
    set pass 1
end

if get_arg_flag "command --flag" "--fun-with"
    echo "Not expecting --fun-with to be flagged"
    set pass 1
end

exit $pass
