#!/usr/bin/env fish

set d (mktemp --directory)

vantage --app "$d" config FOO BAR
set o (cat "$d/.vantage")

rm -rf "$d"

test "$o" = "FOO=BAR"

set s $status

if test $s -ne 0
    echo "    Thought .vantage file should contain FOO=BAR, it contained $o"
end

exit $s
