#!/usr/bin/env fish

set d (mktemp --directory)
echo "VG_FOO=BAR" > "$d/.vantage"

set o (vantage --app "$d" config)

rm -rf "$d"

switch "$o"
    case "*VG_FOO=BAR*"
    case '*'
        echo "Config did not contain VG_FOO"
        echo $o
        exit 1
end

switch "$o"
    case "*VG_APP_DIR=$d*"
    case '*'
        echo "Config did not contain VG_APP_DIR"
        echo $o
        exit 1
end

switch "$o"
    case "*VG_ENV_FILE=*"
    case '*'
        echo "Config did not contain VG_ENV_FILE"
        echo $o
        exit 1
end

switch "$o"
    case "*VG_PLUGIN_PATH=*"
    case '*'
        echo "Config did not contain VG_PLUGIN_PATH"
        echo $o
        exit 1
end

switch "$o"
    case "*VG_PARENT_ENV_FILE=*"
    case '*'
        echo "Config did not contain VG_PARENT_FILE"
        echo $o
        exit 1
end
