#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob

case "$1" in
    build)
        if [ -z $VG_APP_DIR ]; then echo "VG_APP_DIR is not set"; exit 1 ; fi
        docker build \
            --tag vg_app \
            "$VG_APP_DIR"
        exit $VG_VALID_EXIT
        ;;
    run)
        docker run \
            --env-file "$VG_ENV_FILE" \
            vg_app
        exit $VG_VALID_EXIT
        ;;
    shell)
        docker run \
            --env-file "$VG_ENV_FILE" \
            --interactive \
            --tty \
            --rm \
            --net=host \
            vg_app bash
        exit $VG_VALID_EXIT
        ;;
    help)
        echo "    app build - Build your app"
        echo "    app run - Spin up your app"
        ;;
    *)
        exit $VG_NOT_IMPLEMENTED_EXIT
        ;;
esac
