#!/usr/bin/env fish

set here (dirname (status --current-filename))

set --export --global VG_PLUGIN_PATH $VG_PLUGIN_PATH "$here/plugins"

vantage foo

set s $status

if test $s -ne 42
    echo "    Thought plugin exit code should be 42, it was $s"
else
    set s 0
end

exit $s
