#!/usr/bin/env fish

set o (vantage env FOO)
test -z "$o"

set s $status

if test $s -ne 0
    echo "    Thought env variable FOO should be empty, it was $o"
end

vantage env FOO BAR
set o (vantage env FOO)

test "$o" = "BAR"

set s $status

if test $s -ne 0
    echo "    Thought env variable FOO should be BAR, it was $o"
end

exit $s
