#!/usr/bin/env fish

set --export --global VG_PLUGIN_PATH $VG_PLUGIN_PATH "$VG_APP_DIR/tests/run_pre_override/one" "$VG_APP_DIR/tests/run_pre_override/two"

set o (vantage foo)

test "$o" = "pre"

set s $status

if test $s -ne 0
    echo "    Thought plugin output should be pre, it was $o"
end

exit $s
