#!/bin/bash
set -e

function help {
    cat << EOF >&2
usage: vantage __default_env_list

List all of the available env files for this app.

EOF
}

if [ -n "$VG_SHOW_HELP" ]; then
    help
    exit
fi

ls "$VG_ENV_DIR"
