#!/bin/bash
set -e

function help {
    cat << EOF >&2
usage: vantage __plugins list|install|uninstall [PLUGIN_NAME]

Commands:

    vg __plugins list - List all installed plugins
    vg __plugins install NAME - Install a plugin
    vg __plugins uninstall NAME - Uninstall a plugin

See the GitHub repo for more details (https://github.com/vantage-org/vantage)

EOF
}

if [ -n "$VG_SHOW_HELP" ]; then
    help
    exit
fi

case "$1" in
    list|ls|show)
        ls -1 "$VG_INSTALL_DIR/plugins/installed"
        ;;
    install|add)
        name="$2"
        set +e
        git ls-remote "$name" 2> /dev/null
        if [ $? -ne 0 ]; then
            name="https://github.com/vantage-org/$name.git"
        fi
        set -e
        cd "$VG_INSTALL_DIR/plugins/installed"
        git clone "$name" --recursive
        cd - > /dev/null
        ;;
    uninstall|remove|rm)
        rm -rf "$VG_INSTALL_DIR/plugins/installed/$2"
        ;;
    *)
        help
        exit 1
        ;;
esac
