#!/bin/bash
set -e

function help {
    cat << EOF >&2
vantage: __update: usage: vantage __update [PLUGIN_NAME]

Running 'vg __update' will update vantage core by running 'git fetch' and then 
'git reset --hard'

Running 'vg __update NAME' will update the installed plugin (using git as for
core updates)

EOF
}

if [ -n "$VG_SHOW_HELP" ]; then
    help
    exit
fi

case "$1" in
    ""|vantage|vg)
        D="$VG_INSTALL_DIR"
        ;;
    *)
        D="$VG_INSTALL_DIR/plugins/installed/$1"
        if [ ! -d "$D" ]; then
            echo "vantage: __update: Plugin directory for $1 not found" >&2
            exit 1
        fi
        ;;
esac

cd "$D"
git fetch --all
git reset --hard origin/master
cd - > /dev/null
