#!/bin/bash
set -e

function help {
    cat << EOF >&2
usage: vantage __update [PLUGIN_NAME]

Vantage and its plugins are installed and updated using git. Performing an
update simply runs 'git fetch' and 'git reset --hard' on the installation
folder.

Commands:

    vg __update - Update vantage itself
    vg __update NAME - Update the named plugin

See the GitHub repo for more details (https://github.com/vantage-org/vantage)

EOF
}

if [ -n "$VG_SHOW_HELP" ]; then
    help
    exit
fi

case "$1" in
    ""|vantage|vg)
        D="$VG_INSTALL_DIR"
        ;;
    *)
        D="$VG_INSTALL_DIR/plugins/installed/$1"
        if [ ! -d "$D" ]; then
            echo "vantage: __update: Plugin directory for $1 not found" >&2
            exit 1
        fi
        ;;
esac

cd "$D"
git fetch --all
git reset --hard origin/master
cd - > /dev/null
