#!/usr/bin/env fish
set here (dirname (status --current-filename))

set --export --global VG_PLUGIN_PATH $VG_PLUGIN_PATH "$here/one" "$here/two"

set o (vantage foo)

test "$o" = "peri peri"

set s $status

if test $s -ne 0
    echo "    Thought plugin output should be peri peri, it was $o"
end

exit $s
