#!/usr/bin/env fish
switch "$argv"
    case 'summary'
        echo "  test - Run vantage tests"
    case '*'
        echo "vantage test"
        echo "  Run every test"
        echo "vantage test NAME"
        echo "  Only run NAME"
        echo "  e.g. vantage test load_config"
end
