#!/usr/bin/env fish
switch "$argv"
    case 'summary'
        echo "  test - Run vantage tests"
    case '*'
        echo "\
vantage test
  Run every test
vantage test NAME
  Run the tests only for the NAME plugin"
end
