#!/usr/bin/env fish

function run
    set path "$argv[2]"
    set test_case (basename "$path")
    set output (eval "$path/run")
    set code $status
    if test $status -eq 0
        echo "$argv[1]: $test_case OK"
    else
        echo "$argv[1]: $test_case FAIL"
        for o in $output
            echo "  $o"
        end
    end
end

for t in (ls "$VG_APP_DIR/tests/")
    run "vantage" "$VG_APP_DIR/tests/$t"
end
for path in $VG_PLUGIN_PATH
    for plugin in (ls "$path")
        if test -d "$path/$plugin/tests"
            for t in (ls "$path/$plugin/tests")
                run "$plugin" "$path/$plugin/tests/$t"
            end
        end
    end
end
