#!/usr/bin/env fish

function run
    set path "$argv[2]"
    set test_case (basename "$path")
    set output (eval "$path/run")
    if test $status -eq 0
        echo "$argv[1]: $test_case OK"
    else
        echo "$argv[1]: $test_case FAIL"
        for o in $output
            echo "  $o"
        end
    end
end

switch "$argv"
    case ''
        vantage test vantage
        for path in $VG_PLUGIN_PATH
            for plugin in (ls "$path")
                vantage test "$plugin"
            end
        end
    case 'vantage' 'vg'
        for t in (ls "$VG_INSTALL_DIR/tests")
            run "vantage" "$VG_INSTALL_DIR/tests/$t"
        end
    case '*'
        for path in $VG_PLUGIN_PATH
            if test -d "$path/$argv/tests"
                for t in (ls "$path/$argv/tests")
                    run "$argv" "$path/$argv/tests/$t"
                end
            end
        end
end
