#!/usr/bin/env fish
switch "$argv"
    case 'summary'
        echo "  env - Read and write your app's environment values"
    case '*'
        echo "\
vantage env
  Print the entire environment
vantage env KEY
  Print the value of env variable KEY
  e.g. vantage env DATABASE_URL
vantage env KEY VALUE
  Set env value KEY to VALUE"
end
