#!/usr/bin/env fish

switch (count $argv)
    case '0'
        set here (dirname (status --current-filename))
        env -i "$here/cave" "$VG_ENV_FILE"
    case '1'
        for line in (vantage env)
            set kv (echo $line | tr "=" "\n")
            if test "$kv[1]" = "$argv[1]"
                echo $kv[2]
                exit 0
            end
        end
        exit 1
    case '2'
        if test -f "$VG_ROOT_ENV_FILE"
            set tmp (mktemp)
            cp "$VG_ROOT_ENV_FILE" "$tmp"
            echo "$argv[1]=$argv[2]" >> "$tmp"
            vantage --env "$tmp" env > "$VG_ROOT_ENV_FILE"
        end
    case '*'
        echo "I'm not sure what you want me to do..."
        exit 1
end
