#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob

function git_update {
    cd "$1" > /dev/null
    git fetch --all
    git reset --hard origin/master
}

case "$1" in
    install)
        name="$2"
        if [[ "$name" != http://* && "$name" != https://* ]]; then
            name="https://github.com/vantage-org/$name.git"
        fi
        mkdir -p /usr/local/vantage/installed
        cd /usr/local/vantage/installed
        git clone "$name"
        exit $VG_VALID_EXIT
        ;;
    list|ls)
        ls -1 /usr/local/vantage/installed
        ;;
    help)
        echo "    plugin install NAME|URL - Install this vantage plugin"
        echo "    plugin install list|ls - List all installed plugins"
        ;;
    *)
        exit $VG_NOT_IMPLEMENTED_EXIT
        ;;
esac
