#!/usr/bin/env fish
switch "$argv"
    case 'summary'
        echo "  config - Read and write vantage config values"
    case '*'
        echo "vantage config"
        echo "  Print every vantage config value known"
        echo "vantage config KEY"
        echo "  Print the value of config variable KEY"
        echo "  e.g. vantage config VG_APP_DIR"
        echo "vantage config KEY VALUE"
        echo "  Set config value KEY to VALUE"
        echo "  Config values set like this will be stored in $VG_APP_DIR/.vantage"
end
