#!/usr/bin/env fish
switch "$argv"
    case 'summary'
        echo "  config - Read and write vantage config values"
    case '*'
        echo "\
vantage config
  Print every vantage config value known
vantage config KEY
  Print the value of config variable KEY
  e.g. vantage config VG_APP_DIR
vantage config KEY VALUE
  Set config value KEY to VALUE
  Config values set like this will be stored in $VG_APP_DIR/.vantage"
end
