#!/usr/bin/env fish
switch (count $argv)
    case '0'
        set | grep "^VG_" --colour=NEVER
    case '1'
        echo "$$argv[1]"
    case '*'
        echo "$argv[1]=$argv[2..-1]" >> "$VG_APP_DIR/.vantage"
end
