#!/usr/bin/env fish

set --erase VG_APP_DIR

set d (mktemp --directory)

mkdir --parents "$d/one/two"
touch "$d/.vantage"

cd "$d/one/two"
set o (vantage config VG_APP_DIR)
cd -

rm -rf "$d"

test "$o" = "$d"

set s $status

if test $s -ne 0
    echo "    Thought VG_APP_DIR should be $d, it was $o"
end

exit $s
