#!/usr/bin/env fish

set o (vantage env FOO)

test "$o" = ""

set s $status

if test $s -ne 0
    echo "    Thought env variable FOO shouldn't exist yet, it was $o"
end

set o (vantage --var FOO=BAR env FOO)

test "$o" = "BAR"

set s $status

if test $s -ne 0
    echo "    Thought env variable FOO should be BAR, it was $o"
end

exit $s
