#!/usr/bin/env fish
switch "$argv"
    case 'summary'
        echo "  help - Print help on using vantage"
    case '*'
        echo "\
vantage help
  Print a list of commands
vantage help COMMAND
  Show more detailed help on a specific command"
end
