#!/usr/bin/env fish
set here (dirname (status --current-filename))

set --export --global VG_PLUGIN_PATH $VG_PLUGIN_PATH "$here/plugins"

set o (vantage bar)

test "$o" = "foo"

set s $status

if test $s -ne 0
    echo "    Thought plugin output should be foo, it was $o"
end

exit $s
