#!/usr/bin/env fish

set --export --global VG_PLUGIN_PATH $VG_PLUGIN_PATH "$VG_APP_DIR/tests/run_plugin_using_alias/plugins"

set o (vantage bar)

test "$o" = "foo"

set s $status

if test $s -ne 0
    echo "    Thought plugin output should be foo, it was $o"
end

exit $s
